### ISSUE TITLE
Add Dependabot configuration for automated dependency updates

### ISSUE THREAD

**Issue by vtakaj** [vtakaj/natural-shift-planner#61]
## Description
Add Dependabot configuration to automatically keep dependencies up to date and secure.

## Motivation
- Automatically detect and fix security vulnerabilities in dependencies
- Keep packages up to date with the latest features and bug fixes
- Reduce manual work of checking and updating dependencies

## Proposed Implementation
Create `.github/dependabot.yml` with configuration for:
- Python dependencies (via pip/uv)
- GitHub Actions dependencies
- Weekly update schedule

## Benefits
- 🔒 Improved security through automated vulnerability detection
- 📦 Dependencies stay current without manual intervention
- 🤖 Automated pull requests with detailed changelogs
- ⏰ Configurable update frequency

## Example Configuration
```yaml
version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

## Tasks
- [ ] Create `.github/dependabot.yml` configuration file
- [ ] Configure update schedule and limits
- [ ] Test with initial dependency updates
