### ISSUE TITLE
fix: GitHub Actions denied permission to push to ghcr.io

### ISSUE THREAD

**Issue by vtakaj** [vtakaj/natural-shift-planner#91]
## Summary
GitHub Actions workflow is failing to push Docker images to GitHub Container Registry (ghcr.io) due to insufficient permissions.

## Error Details
```
ERROR: failed to solve: failed to push ghcr.io/vtakaj/natural-shift-planner/shift-scheduler:main: denied: installation not allowed to Create organization package
```

**Workflow Run**: https://github.com/vtakaj/natural-shift-planner/actions/runs/15659913114/job/44116134776

## Problem
The GitHub Actions workflow doesn't have permission to create packages in the organization's container registry. This happens when:
1. The repository is trying to push to ghcr.io for the first time
2. The GITHUB_TOKEN doesn't have sufficient permissions
3. The repository/organization settings don't allow package creation

## Root Cause
The error message "installation not allowed to Create organization package" indicates that either:
- The GitHub App/Actions doesn't have package write permissions
- The repository needs explicit permissions to create packages
- The organization settings might be blocking package creation

### Solution 1: Update Repository Permissions
Add explicit package write permissions to the workflow:

```yaml
jobs:
  build:
    permissions:
      contents: read
      packages: write  # Add this permission
```

### Solution 2: Update the Complete Workflow
Ensure all necessary permissions are set in the workflow file:

```yaml
name: Application Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write
  pull-requests: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/shift-scheduler
```

### Solution 3: Repository Settings
1. Go to Repository Settings → Actions → General
2. Under "Workflow permissions", ensure:
   - "Read and write permissions" is selected
   - "Allow GitHub Actions to create and approve pull requests" is checked (if needed)

### Solution 4: Use Personal Access Token (Alternative)
If organization restrictions prevent using GITHUB_TOKEN:
1. Create a Personal Access Token with `write:packages` scope
2. Add it as a repository secret (e.g., `GHCR_TOKEN`)
3. Update the workflow:

```yaml
- name: Login to Container Registry
  uses: docker/login-action@v3
  with:
    registry: ${{ env.REGISTRY }}
    username: ${{ github.actor }}
    password: ${{ secrets.GHCR_TOKEN }}  # Use PAT instead
```

## Expected Behavior
- GitHub Actions should successfully build Docker images
- Images should be pushed to ghcr.io without permission errors
- Multi-platform images (amd64/arm64) should be published

## Priority
**High** - This blocks all automated deployments and container image publishing.

## Acceptance Criteria
- [ ] Docker images build successfully in GitHub Actions
- [ ] Images are pushed to ghcr.io without permission errors
- [ ] Workflow completes successfully for both push and PR events
- [ ] Multi-platform images are available in the container registry

## Related
- Previous Docker fix PR: #90
- Original Docker issue: #89

## Labels
- bug
- github-actions
- infrastructure
- high-priority
- permissions
